### ISSUE TITLE
Spyse API Key (Update)

### ISSUE THREAD

**Issue by Greg-spec** [w1th0ut/red-ocean#1]
You previously used one of our services a part of your development. Most likely it was Spyse itself, Findsubdomains, Cert DB or DNS table. We want to notify you that we are releasing our new and updated Spyse search engine. We hope you will be interested in testing and implementing a much broader functionality to your developments. Thanks for being with us.

**Comment by w1th0ut** [comment]
hello @Greg-spec ,
thanks for notify me about new updated Spyse search engine, it is interesting for me, for the future, i will try it.

thanks.
